receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  # OpenObserve用エクスポーター
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default
    auth:
      authenticator: basicauth/openobserve

  # Grafana LGTM用エクスポーター（両方に送りたい場合）
  otlp:
    endpoint: http://lgtm:4317
    tls:
      insecure: true

extensions:
  basicauth/openobserve:
    client_auth:
      username: root@example.com
      password: Complexpass#123

service:
  extensions: [basicauth/openobserve]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp] # 両方に送る場合は並記
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve, otlp]